### ISSUE TITLE
Code Editor indentation problems

### ISSUE THREAD

**Issue by se5a** [kaosat-dev/CoffeeSCad#84] opened 2013-03-26 03:37 UTC
Code editor is a little too sensitive about indentation, 
also in some places a carriage return will put the next line at an incorrect indentation, i.e. a carriage return after an open bracket. (then give an error about it)
also it doesn't like this formating:

<pre>
cube3 = new Cube
(
   {
      size: [10, 15, 5] #size can be an array
      center: true #center: true centers the object
   }
)
</pre>

yet does not error or warn. (it just does a default cube)

**Comment by kaosat-dev** [comment] 2013-03-28 21:39
Hello Jonathan, I checked and double checked the indentation issues, i can reproduce it, and it seems to be working correctly : if you are already in an indentated block , it keeps the indentation on carriage return.
If you find the exact case where it fails, please let me know, I'll fix it :)

For the example you mention, it is normal, coffeescript will interpret that as just a call to new Cube() and then an expression inside the parens.

A few correct ways to write it :

```
cube3 = new Cube(
   {
      size: [10, 15, 5] #size can be an array
      center: true #center: true centers the object
   }
)
```

```
cube3 = new Cube
  size: [10, 15, 5] #size can be an array
  center: true #center: true centers the object
```

(in this case , the elements following the call to "new cube" will be interpreted like an object with keys "size" and "center", no need for parenthesis etc , but indentation should be respected

**Comment by se5a** [comment] 2013-03-30 00:59
you might need to use the pre tag or something to show the formatting there. 
I guess I need to read up on how coffeescript expects indentation. I'm used to python, which doesn't care as long as you're consistent within an indented section.

**Comment by kaosat-dev** [comment] 2013-04-01 21:39
@se5a : Tottally forgot, but I changed the examples above to have correct indentation (and be displayed as code aswell:) 
Normally, as far as I can tell , coffeescript indentation is very close to Python's (I keep switching between the two and nothing stood out for now).
But yeah the coffeescript docs are well worth a read as far as how indentation is interpreted in certain cases.
The section **Objects and Arrays** is particularly of interest in the official documentation at http://coffeescript.org/

**Comment by se5a** [comment] 2013-04-02 22:51
RE: the carriage return, it currently does this:
(pipes ie. | being where the cursor is)

<pre>
cube = new Cube(
               |
</pre>

I'd argue that it _should_ do this:

<pre>
cube = new Cube(
   | 
</pre>

visual studio goes one step further and does the above, until you add a curly bracket, then reformats:

<pre>
cube = new Cube(
   |
cube = new Cube(
{|
</pre>

though that's C# formating. 

Edit: gah, pre does not do what it's suposed to... hope this looks the same to you as it does to me now.

**Comment by se5a** [comment] 2013-04-04 02:56
Oh, and shift tab should go back an indentation. currently it drags everything preceding the cursor to the right, which is a bit wierd.

**Closed as completed** 2013-05-08 22:46 UTC
